### ISSUE TITLE
Code Execution Error

### ISSUE THREAD

**Issue by raneemMMH** [AHR-OCR2024/Arabic-Handwriting-Recognition#3]
hi ,
When I try to run it, I get the following error:
"× Error: Connection error. Please ensure you are connected to the internet, or the server might be unavailable."
Additionally, the model is not linked to the code, so I am unable to execute the Jupyter scripts.

**Comment by AHR-OCR2024** [comment]
The hosted application contacts a backend which we set up temporarily using a local machine that was exposed to the internet.
As an alternative you should provide your own backend using this button:

![image](https://github.com/user-attachments/assets/8327aefc-db66-47eb-95a3-2e7ebbd0de12)

enter it in the format:
**https://hostname.domain/upload-image**
where "hostname.domain" is the url of the backend, upload-image is the name of the api end point in the backend code.

As for the pretrained models, they will be uploaded in a couple of days.

**Comment by AHR-OCR2024** [comment]
The model link has been added to the readme file.
